### ISSUE TITLE
missing package

### ISSUE THREAD

**Issue by bckelley** [drewgrif/debian-hyprland#1]
I get unable to locate package yad?

**Comment by dwilliam62** [comment]
> I get unable to locate package yad?

Are you running testing(trixie) or SID?   YAD was removed from those.  

 Try grabbing it from here

  https://packages.debian.org/bookI%20get%20unable%20to%20locate%20package%20yad?worm/yad

**Comment by dwilliam62** [comment]
Also this is a fork of the Jakooklit repo.  https://github.com/JaKooLit/Debian-Hyprland   This has a link to his discord server if you have questions or issues.   This only works on debian testing and SID.   if you are using ubuntu that is a different repo.  Some ppl have tried to use this on ubuntu and it won't work properly   Regards  Don

**Comment by dwilliam62** [comment]
Also this is a fork of the Jakooklit repo.  https://github.com/JaKooLit/Debian-Hyprland   This has a link to his discord server if you have questions or issues.   This only works on debian testing and SID.   if you are using ubuntu that is a different repo.  Some ppl have tried to use this on ubuntu and it won't work properly   Regards  Don

**Comment by bckelley** [comment]
thank you! i will try that package!
